apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
  labels:
    app: expense-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: expense-tracker:latest
        ports:
        - containerPort: 3000
        env:
        - name: VITE_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-url
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-anon-key
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"