apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
data:
  supabase-url: aHR0cHM6Ly96a252cGJjeWp1YWZ1YW92bWRidC5zdXBhYmFzZS5jbw==
  supabase-anon-key: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5wcmJuWndZbU41YW5WaFpuVmhiM1p0WkdKMElpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTkRNeU5EWTNNVE1zSW1WNGNDSTZNakExT0RneU1qY3hNMzAudU5wbnM0RW1fdG9yaWxrN0VsUjdTUDVsZ0hvVzBCQlV3MGJleWVCbkxuOA==